/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SyllabusRouteImport } from './routes/syllabus'
import { Route as RevisionsRouteImport } from './routes/revisions'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const SyllabusRoute = SyllabusRouteImport.update({
  id: '/syllabus',
  path: '/syllabus',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisionsRoute = RevisionsRouteImport.update({
  id: '/revisions',
  path: '/revisions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/revisions': typeof RevisionsRoute
  '/syllabus': typeof SyllabusRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/revisions': typeof RevisionsRoute
  '/syllabus': typeof SyllabusRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/revisions': typeof RevisionsRoute
  '/syllabus': typeof SyllabusRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/progress'
    | '/revisions'
    | '/syllabus'
    | '/admin/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/progress'
    | '/revisions'
    | '/syllabus'
    | '/admin/login'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/progress'
    | '/revisions'
    | '/syllabus'
    | '/admin/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  RevisionsRoute: typeof RevisionsRoute
  SyllabusRoute: typeof SyllabusRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/syllabus': {
      id: '/syllabus'
      path: '/syllabus'
      fullPath: '/syllabus'
      preLoaderRoute: typeof SyllabusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revisions': {
      id: '/revisions'
      path: '/revisions'
      fullPath: '/revisions'
      preLoaderRoute: typeof RevisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  RevisionsRoute: RevisionsRoute,
  SyllabusRoute: SyllabusRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
